# Generated by Django 5.1.4 on 2025-01-03 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default=None)),
                ('dateCreated', models.DateField()),
                ('createdBy', models.CharField(max_length=255)),
                ('allowVotes', models.BooleanField(default=False)),
                ('allowAdds', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Lists',
            },
        ),
        migrations.CreateModel(
            name='ListSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.lists')),
            ],
            options={
                'verbose_name_plural': 'ListSong',
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=200)),
                ('song_artist', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('songlists', models.ManyToManyField(through='main.ListSong', to='main.lists')),
            ],
            options={
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.AddField(
            model_name='listsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.songs'),
        ),
        migrations.AddField(
            model_name='lists',
            name='listsongs',
            field=models.ManyToManyField(through='main.ListSong', to='main.songs'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lists')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.songs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
