# Generated by Django 5.1.15 on 2026-03-12 23:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('share_link_active', models.BooleanField(default=False)),
                ('invite_only', models.BooleanField(default=False, help_text='When enabled with share link, the user must also have an email invite to join via the link.')),
                ('allow_votes', models.BooleanField(default=True)),
                ('allow_adds', models.BooleanField(default=False, help_text='Allow contributors to add songs to this list.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('spotify_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('spotify_url', models.URLField(blank=True, null=True)),
                ('album_art_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['artist', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ListSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_songs_added', to=settings.AUTH_USER_MODEL)),
                ('music_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_songs', to='main.musiclist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_songs', to='main.song')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('music_list', 'song')},
            },
        ),
        migrations.CreateModel(
            name='ListInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to=settings.AUTH_USER_MODEL)),
                ('music_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='main.musiclist')),
            ],
            options={
                'unique_together': {('music_list', 'email')},
            },
        ),
        migrations.CreateModel(
            name='ListCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('contributor', 'Contributor')], default='contributor', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborators_added', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL)),
                ('music_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='main.musiclist')),
            ],
            options={
                'unique_together': {('music_list', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('list_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main.listsong')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'list_song')},
            },
        ),
    ]
