# Generated by Django 5.1.4 on 2025-01-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song_artist',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='songs',
            name='song_title',
            field=models.CharField(max_length=500),
        ),
    ]
