# Generated by Django 5.1.4 on 2025-01-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_songs_song_artist_alter_songs_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='list_images'),
        ),
    ]
